#!/bin/bash
#only use in projects without a package.json file.

args=("$*")
staticForeverDir="~/cs340/example/diagnostic/node_modules/forever/bin/forever"
HOSTN=$(env | grep HOSTNAME);
StartUpFile="diagnostic.js"
FileNM="4ever.tmp"
PORTNUM=(5301)

echo "Only use on OSU flip servers"
echo $HOSTN
#echo $args
#echo $staticForeverDir

if [ $1 == "start" ] && [ ! -z $HOSTN ]
then
	echo -e "\nCreating a process info file"
	rm $FileNM
	touch $FileNM

	echo "HOSTNAME: $HOSTN" > $FileNM
	echo "STARTUPFILE: $StartUpFile" >> $FileNM
	echo "PORTNUMBER: $PORTNUM" >> $FileNM

	eval "$staticForeverDir start $StartUpFile $PORTNUM"
elif [ $1 == "stop" ]
then
	eval "$staticForeverDir stop $2"
elif [ $1 == "tmpstart" ]
then
	eval "node start $StartUpFile $PORTNUM"
elif [ $1 == "list" ]
then
	eval "$staticForeverDir list"
else
	echo "$0: command not found"	
fi


