#!/bin/bash
args=("$*")
staticForeverDir="~/cs340/example/diagnostic/node_modules/forever/bin/forever"
HOSTN=$(env | grep HOSTNAME);
StartUpFile="diagnostic.js"
FileNM="4ever.tmp"
PORTNUM=(5301)

echo "Only use on OSU flip servers"
echo $HOSTN
#echo $args
#echo $staticForeverDir

if [ $1 == "start" ] && [ ! -z $HOSTN ]
then
	echo "creating a hostname file"
	rm $FileNM
	touch $FileNM

	echo "HOSTNAME: $HOSTN" > $FileNM
	echo "STARTUPFILE: $StartUpFile" >> $FileNM
	echo "PORTNUMBER: $PORTNUM" >> $FILENM

	eval "$staticForeverDir start $StartUpFile $PORTNUM"	
fi


